/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entity.SmartPhone;
import entity.User;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Youssef-pc
 */
public class SmartPhoneForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form SmartPhoneForm
     */
    
    private Long id;
    private Long idPhone;
    public static SmartPhoneForm instance;
    private DefaultTableModel model;
    private DefaultComboBoxModel model1;
    
    public SmartPhoneForm(String title) throws NamingException {
        super(title); 
    }
    public SmartPhoneForm() throws NamingException{
        initComponents();
        model =(DefaultTableModel) ListPhone.getModel();
        model1=(DefaultComboBoxModel) UserBox.getModel();
        load();
        loadCombo();
    }
    
    public void loadCombo() throws NamingException{
        for(User u:TestUserClient.lookUpUserRemote().findAll()){
            model1.addElement(u);
        }
    }
    
    public void load() throws NamingException{
        model.setRowCount(0);
        //model1.removeAllElements();
//        for(User u:TestUserClient.lookUpUserRemote().findAll()){
//            model1.addElement(u);
//        }
        for(SmartPhone sp:TestUserClient.lookUpSmartPhoneRemote().findAll()){
            model.addRow(new Object[]{
                sp.getId(),
                sp.getImei(),
                sp.getUser().getNom()
            });
        }
    }
    public static SmartPhoneForm getInstance() throws NamingException{
        if(instance==null)
            instance= new SmartPhoneForm();
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UserBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        imei_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListPhone = new javax.swing.JTable();
        ajouter_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        supprimer_btn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion Des SmartPhones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(204, 0, 0)));
        jPanel1.setToolTipText("");

        jLabel2.setText("Imei");

        UserBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imei_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(UserBox, 0, 169, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(imei_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UserBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ListPhone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Imei", "User"
            }
        ));
        ListPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListPhoneMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListPhone);

        ajouter_btn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ajouter_btn.setForeground(new java.awt.Color(0, 124, 0));
        ajouter_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Add-icon (1).png"))); // NOI18N
        ajouter_btn.setText("Ajouter");
        ajouter_btn.setMargin(new java.awt.Insets(5, 14, 5, 14));
        ajouter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter_btnActionPerformed(evt);
            }
        });

        update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button-round-reload-icon.png"))); // NOI18N
        update_btn.setText("Modifier");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        supprimer_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Delete-icon.png"))); // NOI18N
        supprimer_btn.setText("Supprimer");
        supprimer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(81, 81, 81))
                    .addComponent(update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supprimer_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(ajouter_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ajouter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supprimer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Gestion Des SmartPhones");
        jPanel1.getAccessibleContext().setAccessibleDescription("Gestion Des SmartPhones");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserBoxActionPerformed
        // TODO add your handling code here:
        id=((User)(UserBox.getSelectedItem())).getId();
    }//GEN-LAST:event_UserBoxActionPerformed

    private void ListPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListPhoneMouseClicked
        // TODO add your handling code here:
        idPhone=(Long) model.getValueAt(ListPhone.getSelectedRow(), 0);
        imei_txt.setText(model.getValueAt(ListPhone.getSelectedRow(), 1).toString());
        UserBox.setSelectedItem(model.getValueAt(ListPhone.getSelectedRow(), 2));
    }//GEN-LAST:event_ListPhoneMouseClicked

    private void ajouter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter_btnActionPerformed
        // TODO add your handling code here:
        String imei=imei_txt.getText();
        try {
            TestUserClient.lookUpSmartPhoneRemote().create(new SmartPhone(imei,TestUserClient.lookUpUserRemote().findById(id)));
            JOptionPane.showMessageDialog(this,"le SmartPhone est ajouté ");
            load();
        } catch (NamingException ex) {
            Logger.getLogger(SmartPhoneForm.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_ajouter_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        String imei=imei_txt.getText();
        try {
            TestUserClient.lookUpSmartPhoneRemote().update(new SmartPhone(imei,TestUserClient.lookUpUserRemote().findById(id)));
            JOptionPane.showMessageDialog(this,"le SmartPhone est mis à jour ");
            load();
        } catch (NamingException ex) {
            Logger.getLogger(SmartPhoneForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_update_btnActionPerformed

    private void supprimer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimer_btnActionPerformed
        // TODO add your handling code here:
        int reponse=JOptionPane.showConfirmDialog(this," voulez vous supprimer cet utilisateur ?");
        if(reponse ==0){
            try {
                TestUserClient.lookUpSmartPhoneRemote().deleteById(idPhone);
                JOptionPane.showMessageDialog(this,"le SmartPhone est supprimé");
                load();
            } catch (NamingException ex) {
                Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_supprimer_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListPhone;
    private javax.swing.JComboBox UserBox;
    private javax.swing.JButton ajouter_btn;
    private javax.swing.JTextField imei_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton supprimer_btn;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
